# Generated by Django 5.2.8 on 2025-11-28 11:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la salle')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('tenant_id', models.CharField(db_index=True, max_length=100, verbose_name='ID du centre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Couleur (hex)')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Durée par défaut (min)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('tenant_id', models.CharField(db_index=True, max_length=100, verbose_name='ID du centre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de cours',
                'verbose_name_plural': 'Types de cours',
                'ordering': ['name'],
                'unique_together': {('name', 'tenant_id')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du cours')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('max_participants', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre max de participants')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planifié'), ('ONGOING', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='SCHEDULED', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('tenant_id', models.CharField(db_index=True, max_length=100, verbose_name='ID du centre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(limit_choices_to={'role__in': ['COACH', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='Coach')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='bookings.coursetype', verbose_name='Type de cours')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='bookings.room', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-date', '-start_time'],
                'unique_together': {('coach', 'date', 'start_time', 'tenant_id')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('CANCELLED', 'Annulé'), ('COMPLETED', 'Complété'), ('NO_SHOW', 'Absent')], default='CONFIRMED', max_length=20, verbose_name='Statut')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de réservation')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('checked_in', models.BooleanField(default=False, verbose_name='Présent')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('tenant_id', models.CharField(db_index=True, max_length=100, verbose_name='ID du centre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='members.member', verbose_name='Membre')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-booking_date'],
                'unique_together': {('course', 'member')},
            },
        ),
    ]
