# Generated by Django 5.2.7 on 2025-11-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_add_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du type'),
        ),
    ]
