# Generated by Django 5.2.7 on 2025-11-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymcenter',
            name='subdomain',
            field=models.CharField(default='default_subdomain', max_length=100),
        ),
        migrations.AlterField(
            model_name='gymcenter',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='tenant ID'),
        ),
    ]
