# Generated by Django 5.2.7 on 2025-10-30 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymcenter',
            name='subdomain',
            field=models.CharField(default='default-subdomain', help_text='Sous-domaine unique (ex: powerfit pour powerfit.gymflow.com)', max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Le sous-domaine doit contenir uniquement des lettres minuscules, chiffres et tirets. Il ne peut pas commencer ou finir par un tiret.', regex='^[a-z0-9]([a-z0-9-]*[a-z0-9])?$')], verbose_name='sous-domaine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gymcenter',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='tenant ID'),
        ),
    ]
