services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: gymflow
      POSTGRES_USER: gymflow
      POSTGRES_PASSWORD: gymflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env

volumes:
  pgdata:
