# Generated by Django 5.2.7 on 2025-11-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscriptionplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
