# Generated by Django 5.2.7 on 2025-11-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscriptionplan_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='stripe_session_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
