# Generated by Django 5.2.7 on 2025-10-29 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'role': 'MEMBER'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('BEGINNER', 'Débutant'), ('INTERMEDIATE', 'Intermédiaire'), ('ADVANCED', 'Avancé'), ('PRO', 'Professionnel')], default='BEGINNER', max_length=20)),
                ('goals', models.TextField(blank=True, verbose_name='Objectifs du membre')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='members.memberprofile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('member', 'date')},
            },
        ),
    ]
