# Generated by Django 5.2.7 on 2025-11-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID du centre'),
        ),
    ]
