# Generated by Django 5.2.7 on 2025-11-02 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?[0-9]{8,17}$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'Inactif'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('EXPIRED', 'Expiré')], default='INACTIVE', max_length=20),
        ),
    ]
