# Generated by Django 5.2.8 on 2025-11-28 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Exercise Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='beginner', max_length=20)),
                ('equipment_needed', models.CharField(blank=True, help_text='Équipement nécessaire', max_length=200)),
                ('video_url', models.URLField(blank=True, help_text='Lien vers vidéo de démonstration', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exercises', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='coaching.exercisecategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('completed', 'Terminé'), ('archived', 'Archivé')], default='draft', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_weeks', models.IntegerField(help_text='Durée en semaines')),
                ('goal', models.TextField(help_text='Objectif principal du programme')),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('target_body_fat', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes du coach')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID du centre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_programs', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_programs', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('chest', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de poitrine')),
                ('waist', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de taille')),
                ('hips', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de hanches')),
                ('arms', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de bras')),
                ('thighs', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de cuisses')),
                ('front_photo', models.ImageField(blank=True, null=True, upload_to='progress/')),
                ('side_photo', models.ImageField(blank=True, null=True, upload_to='progress/')),
                ('back_photo', models.ImageField(blank=True, null=True, upload_to='progress/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_trackings', to='members.member')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_trackings', to='coaching.trainingprogram')),
            ],
            options={
                'verbose_name_plural': 'Progress Trackings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('feeling', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Bon'), ('average', 'Moyen'), ('tired', 'Fatigué'), ('poor', 'Difficile')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to='members.member')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLogExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_completed', models.IntegerField()),
                ('reps_completed', models.CharField(max_length=50)),
                ('weight_used', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaching.exercise')),
                ('workout_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='coaching.workoutlog')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('day_of_week', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')])),
                ('week_number', models.IntegerField(default=1, help_text='Semaine du programme')),
                ('duration_minutes', models.IntegerField(default=60)),
                ('notes', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='coaching.trainingprogram')),
            ],
            options={
                'ordering': ['week_number', 'day_of_week', 'order'],
            },
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='workout_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coaching.workoutsession'),
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.CharField(help_text='Nombre de répétitions (ex: 10-12, 30s)', max_length=50)),
                ('rest_seconds', models.IntegerField(default=60, help_text='Repos entre séries en secondes')),
                ('weight', models.CharField(blank=True, help_text='Poids recommandé (ex: 20kg, bodyweight)', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Instructions spécifiques')),
                ('order', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaching.exercise')),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='coaching.workoutsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
