# Generated by Django 5.2.7 on 2025-11-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID du centre'),
        ),
    ]
